### ISSUE TITLE
Kubernetes Support ?

### ISSUE THREAD

**Issue by ivanpetrovic** [MinimalCompact/thumbor#1]
Hi,

Are you planning to support deployment to Kubernetes ?

Thanks

**Comment by gingerlime** [comment]
Hey @ivanpetrovic,

Yes, absolutely. I have a couple of recipes that I plan to go over, but I'm not (yet?) using Kubernetes in production, so not too confident about it. I'm also not entirely sure what's the best way to "package" those recipes. Perhaps a [helm](https://helm.sh/) chart would be the most robust and flexible way? But I haven't even played with helm yet, let alone created a chart...

Would appreciate any help I can get with it (sample deployment yaml, testing of some templates etc). If you're able to contribute in any way, it would be greatly appreciated.

**Comment by gingerlime** [comment]
Some links I managed to collect so far:

* [GCE examples](https://github.com/APSL/docker-thumbor/tree/master/configuration_examples/google_cloud_engine/production), but they seem a bit outdated (~2 years)
* [thumbor helm chart](https://github.com/cloudposse/charts/tree/master/incubator/thumbor) from about a year ago
* [thumborkube](https://github.com/beenanner/thumborkube), also about a year old

**Comment by ivanpetrovic** [comment]
Unfortunately, those are pretty old :(

What I have for now are deployment files for thumbor, remotecv and redis based on your recipe for remotecv/docker-compose.yml.
They were created using Kompose just to test and they seem to work fine in GKE.
The main issue with GKE is nginx-proxy not beeing able to do
- mountPath: /var/run/docker.sock:/tmp/docker.sock:ro

I also never played with helm, so maybe this can come later.

I have a GKE running and can help with testing and deployment files.

**Comment by gingerlime** [comment]
> Unfortunately, those are pretty old :(

Yes, I'm not sure how valuable these are, especially when kubernetes is moving so fast.

> mountPath: /var/run/docker.sock:/tmp/docker.sock:ro

Maybe [this helps?](https://devops.stackexchange.com/questions/2506/docker-in-kubernetes-deployment)

Otherwise, maybe thumbor-nginx-proxy isn't the best tool for the job and this leaves us looking for another solution, especially for caching (that's the biggest benefit of thumbor-nginx-proxy at the moment). Or you can ditch it completely and only use thumbor / remotecv in your kubernetes deployment, and deal with caching outside it completely (e.g. CDN). 

> They were created using Kompose just to test and they seem to work fine in GKE.

Great to know. Didn't think about using Kompose, although I've heard about it a while ago.

> I have a GKE running and can help with testing and deployment files.

Great. Thanks!

**Comment by ivanpetrovic** [comment]
This is exactly what I ended doing for the socket and it's working.
Will share the deployment files once it's better tested.

I have been using Thumbor for a long time with Varnish for caching but with no webp support :(
I was also planning to do tests with a CDN.

Keep you posted.

Thanks

**Comment by shaneog** [comment]
Ping @ivanpetrovic  - could you provide your deployment files please?

**Comment by ivanpetrovic** [comment]
Hi, I am on holidays. Will post once back.

**Comment by gingerlime** [comment]
Any updates on this one? Or shall I close this if there's no interest in contributing some recipes?

**Comment by verglor** [comment]
Hi @gingerlime, please don't close this issue.
I believe this is a valid feature request regardless of @ivanpetrovic contribution.
Maybe someone else will contribute.

**Comment by ryantxu** [comment]
See #15 -- it required changing the image to respond 200 on `/`, but that should hopefully get baked into Thumbor in the future

**Comment by gingerlime** [comment]
Big thanks to @ryantxu for adding the first Kubernetes recipe! (plus a [readme](https://github.com/MinimalCompact/thumbor/tree/master/recipes/kubernetes)).

The recipe is pretty basic, and I'd love to see more recipes, especially including `nginx-proxy` with caching, but it's a great start. I think I'll close this for now, but contribution for Kubernetes recipes (or anything else) are always welcome.
