### ISSUE TITLE
ARM64 support?

### ISSUE THREAD

**Issue by mpdude** [MinimalCompact/thumbor#102]
From looking the the code here only, am I right assuming that this image does not support running on `arm64` (Apple M1) yet?

What would be your requirements for accepting such a PR?

Have you thought about using GitHub actions to automatically build images?

**Comment by gingerlime** [comment]
Hey @mpdude nice to hear from you again :)

> What would be your requirements for accepting such a PR?

In general, PRs are always welcome :) especially if they improve things. I'm not sure what's involved however, but as long as it's simple and doesn't break existing functionality, we're happy :)

> Have you thought about using GitHub actions to automatically build images?

Yes, I'm already using Semaphore, but perhaps it's better to switch to GH actions. I haven't had the time to dig into it.

Please keep in mind that there's some effort to upgrade to thumbor 7.0, so any other updates might have to take the back seat until this is done...

**Comment by mpdude** [comment]
I don't have any hardware by myself to test this yet, but it looks as if the first teammates will switch to M1 based Macs in the next weeks.

So I have a bit of a personal need, and I have helped another project switch to GHA and ARM64 builds before (although that was PHP-based and I am way more familiar with that).

In short, I'll try to make a first proposal. Seeing that you are soo responsive is a great first step!

**Comment by gingerlime** [comment]
I'm using an M1 Mac, but not sure I have that much time to test things locally ... I think typical thumbor deployment is on servers and they are typically linux, so it doesn't feel like a high-priority use-case, but I guess there are some ARM64 servers out there as well? I'm not against adding this support, if it's simple :) but I won't be able to help much myself unfortunately.

**Comment by mpdude** [comment]
> I'm using an M1 Mac, but not sure I have that much time to test things locally

Have you ever tried running this image as-is on it? Maybe it works right away? 

All I need for the time being is a development-grade Thumbor running for local use only. Although I have read that there are `arm64` based AWS instances (Gravitron?) that seem to be very cheap and might make an interesting use case for image conversion as well…

First check: There is a `python:2.7.18-stretch` Docker image with `arm64v8` support.

Will have to figure out how I can work on this without having an M1 machine myself.

**Comment by gingerlime** [comment]
@mpdude if I run docker desktop on my mac and then run `docker run -p 80:80 minimalcompact/thumbor` it seems to work. I'm not sure what compatibility layers docker desktop / MacOS have in place however, so can't really tell you how "native" this is running.

If AWS provides such instances, then this should hopefully provide a way for you to test things. Good luck!

**Comment by gingerlime** [comment]
This is what docker desktop shows me btw when I run it, but I'm not sure what it means...

<img width="522" alt="image" src="https://user-images.githubusercontent.com/524274/148639755-6d083821-d59a-4357-b054-ef4c6b26ccf4.png">

**Comment by mpdude** [comment]
Seems some work has been put into Docker Desktop on OS X: It can cross-build `amd64`/`arm64` platforms out of the box, and also run `amd64` images via some kind of emulation as you noticed.

By problem is that, for reasons, I need to run an `arm64` Linux virtual machine (via Vagrant) and that all development happens inside that. It seems that when I run Docker inside that VM (and not on the OS X host), I don't get that cross-platform emulation support.

I've tried cross-building a direct `arm64` image on OS X following the real easy instructions in https://www.docker.com/blog/multi-arch-images/.

The `arm64` version, however, fails with:

```
 > [linux/arm64  5/11] RUN pip install --trusted-host None --no-cache-dir    -r /app/requirements.txt:
#20 63.46 Collecting pgmagick==0.7.4
#20 63.50   Downloading pgmagick-0.7.4.tar.gz (362 kB)
#20 66.80 Collecting graphicsmagick-engine==0.1.1
#20 66.86   Downloading graphicsmagick_engine-0.1.1.tar.gz (3.0 kB)
#20 69.16 Collecting cairosvg==1.0.22
#20 69.20   Downloading CairoSVG-1.0.22.tar.gz (30 kB)
#20 74.41 ERROR: Could not find a version that satisfies the requirement opencv-python==4.2.0.32 (from -r /app/requirements.txt (line 23)) (from versions: 3.4.0.14, 3.4.10.37, 4.3.0.38)
#20 74.80 ERROR: No matching distribution found for opencv-python==4.2.0.32 (from -r /app/requirements.txt (line 23))
#20 76.04 WARNING: You are using pip version 20.0.2; however, version 20.3.4 is available.
#20 76.04 You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
```

Now I really don't have any reasonable experience with Python, but to me it seems there is no `arm64`-based image for `opencv-python`?

Applicable issues:
* https://github.com/opencv/opencv-python/issues/366
* https://github.com/opencv/opencv-python/issues/429

If I get all that right, that support has been added rather recently with OpenVC 4.5.3. That version, however, requires Python 3 and thus cannot be used before we switch to Thumbor 7. Version 4.2.0.32 that is listed in `requirements.txt` seems to be the latest version supporting Python 2.7 (https://pypi.org/project/opencv-python/4.2.0.32/).

Does all that make sense? If so, I guess we're stuck until Thumbor 7 is a thing and can take over (when it comes to additional plugins etc.) from Thumbor 6.

**Comment by brutimus** [comment]
@gingerlime Your assessment is correct in that, since no arm64 version of `minimalcompact/thumbor ` exists, Docker for Mac is running it in emulation mode.

I would also like to add a bit of verbal support to the idea of being able to run Thumbor on ARM when the time comes. We run a big chunk of our stack on AWS Elastic Container Service and have recently switched almost all of our production stack over to ARM due to the 20% reduction in costs offered by their Gravitron2 chips. Our Thumbor containers are the only things left on amd64.

Given @mpdude's assessment,  this task looks like one for the post Thumbor 7 / Python 3 TODO list.

**Comment by gingerlime** [comment]
Hope Thumbor 7 moves forward, but there are still some issues with some of the libraries, see #103 

Otherwise, take a look at [imagor](https://github.com/cshum/imagor/). It's API-compatible to Thumbor, and whilst it doesn't have full feature-parity, it's getting closer. My [benchmarks](https://github.com/cshum/imagor/issues/8) also show that it's *much* faster... like not 20% faster, but more like 900% (of course, it really depends on the source image, operations etc).

**Comment by shudack** [comment]
Following the topic.

**Comment by greenfrogs** [comment]
As of [this](https://github.com/MinimalCompact/thumbor/pull/103/commits/d337145ab478475de22c83278530ca3cb73cb9dc) commit on the thumbor 7 branch the build seems to run on ARM64.

**Comment by pfcodes** [comment]
Bump

**Comment by mpdude** [comment]
As the OP, I still have a general interest in getting this solved. However, I won’t be able to come up with a solution near-term.

I had to find an improvised solution last year, which turned out to be running Thumbor on Docker Desktop in OS X, outside of the usual development machine. That solved the immediate need for a solution.

Second, switching to arm64 means switching to Thumbor 7, and before I can do that, I need to get some other Thumbor extensions in other repos compatible for that (including Python 3). That’s a bit of a challenge for me, with practically zero Python experience.

Maybe as a first step, see this comment https://github.com/MinimalCompact/thumbor/issues/102#issuecomment-1008341683, read the referenced blog article, build a Thumbor 7 image on arm64 and report back if it works?

**Comment by gingerlime** [comment]
This should now be available with multiarch builds. See #103

**Comment by f0r3n51c6uy** [comment]
Good evening,
I tried to run the thumbor image on an ARMv64 machine but it throws the following error:
`thumbor-1  | exec /docker-entrypoint.sh: exec format error`
As far as I know, the error is thrown when an executable isn't compatible with the processor architectur. The warning on startup also shows that the image version is incompatible with arm64 architecture.

` ! thumbor The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested  `

I read from the thread that ARM64 should actually be supported. Is this the case? If yes, what do I need to change to get it to work?

**Comment by gingerlime** [comment]
unfortunately I couldn’t get it to work and there wasn’t anyone who picked it up.

https://github.com/MinimalCompact/thumbor/pull/134
