### ISSUE TITLE
Overwrite the default Thumbor host address 0.0.0.0

### ISSUE THREAD

**Issue by roman-stelmakh-emesa** [MinimalCompact/thumbor#108]
Please merge our pull request to have an ability to overwrite the default Thumbor host address 0.0.0.0.
We have to use `::` on EKS with IPv6 ranges.
https://github.com/MinimalCompact/thumbor/pull/107/files

**Comment by gingerlime** [comment]
Will be included with the thumbor 7.x images see #129
