### ISSUE TITLE
Multiple TC_AWS_LOADER_BUCKET

### ISSUE THREAD

**Issue by hu8373551** [MinimalCompact/thumbor#115]
Is it possible to make this work with multiple s3 buckets in tc_aws plugin for thumbor? I'm using multiple cloud front distributions backed by it's own s3 bucket;

**Comment by gingerlime** [comment]
https://github.com/thumbor-community/aws/issues/138 looks like it isn’t possible unfortunately. You might need to run multiple instances of thumbor with custom url rewrite/routing.
