### ISSUE TITLE
Switch CI/CD to GitHub Actions

### ISSUE THREAD

**Issue by danquack** [MinimalCompact/thumbor#117]
To provide more visibility into build flows, it would be helpful to switch the build pipelines into actions.

**Comment by danquack** [comment]
@gingerlime in https://github.com/MinimalCompact/thumbor/pull/116#issuecomment-1521307268, you suggested this. I opened this issue to start the conversation around it, before doing any work. I was curious, how would do you plan on authenticate to docker hub? Would you expose cred secrets within the repository? Would you switch to deploying to GitHub registry instead?

**Comment by gingerlime** [comment]
Thanks again @danquack. I'm not an expert on Github actions, but it (and also semaphore) allow defining secrets and using them, e.g. to authenticate to docker hub. That said, after the docker hub free organizations debacle, I'd be tempted to move to the Github registry anyway. I guess best to tackle one thing at a time though?

I'm slightly worried about how fast (or slow) Github actions might be. I think Semaphore provides faster instances, and it's taking some time even there. But build speed is not a huge concern anyway.

Are you okay starting on your own? if we can get something that builds the images and runs tests, that's a great start. I can then sort out secrets / pushing to the registry. Let me know if you have any questions!

**Comment by gingerlime** [comment]
I think we can close this now :)
