### ISSUE TITLE
multiarch build fails with SIMD

### ISSUE THREAD

**Issue by gingerlime** [MinimalCompact/thumbor#124]
see https://github.com/MinimalCompact/thumbor/actions/runs/4831191062/jobs/8608302819

@danquack can you take a look?

**Comment by gingerlime** [comment]
I thought might be the case, so we would need to refactor the build script and exclude simd from multiarch. Or do you have any other ideas? anyway, would be great if you could take care of it if you can :)

**Comment by danquack** [comment]
@gingerlime I stumbled upon this, maybe its something we can migrate to? https://simd-everywhere.github.io/blog/2020/06/22/transitioning-to-arm-with-simde.html
