### ISSUE TITLE
Upload image - HTTP 405 (Method not allowed)

### ISSUE THREAD

**Issue by Necronum** [MinimalCompact/thumbor#157]
### Thumbor request URL
[POST]
example.com/cdn/image
Both methods from documentation:
- data-binary
- form

### Expected behaviour
Upload image to file system for further usage.

### Actual behaviour
When sending request via postman I get 
`<html><title>405: Method Not Allowed</title><body>405: Method Not Allowed</body></html>`
When checking kuberenetes logs:
`tornado.access:WARNING 405 POST /image (10.42.0.1) 2.25ms`

Other functionality works (healthcheck, unsafe/image etc.)

### Operating system
Ubuntu, k3s, nginx
Thumbor version: latest version of MinimalCompact from ghcr

### Your thumbor.conf
I use yaml with environmental variables. If needed I can provide whole yaml for inspection.
```
      VIRTUAL_HOST:                        example.com
      THUMBOR_PORT:                        80
      ACCESS_CONTROL_ALLOW_ORIGIN_HEADER:  *
      ALLOW_UNSAFE_URL:                    true
      AUTO_WEBP:                           true
      SECURITY_KEY:                        ############
      THUMBOR_NUM_PROCESSES:               2
      FILE_STORAGE_ROOT_PATH:              /home/thumbor/storage
      RESPECT_ORIENTATION:                 true
      UPLOAD_ENABLED:                      true
      UPLOAD_MAX_SIZE:                     10485760
```

**Comment by gingerlime** [comment]
Were you able to find a solution? I'm not using the upload function so it's hard for me to test it unfortunately. It might be worth checking with the upstream Thumbor project.

**Comment by Necronum** [comment]
I changed the approach and used beeyev/thumbor-s3-docker with MinIO. There was no way to find a solution for upload to work properly with nginx. Now I only use thumbor as image optimizer
