### ISSUE TITLE
Wrong version of numpy is installed

### ISSUE THREAD

**Issue by NotWoods** [MinimalCompact/thumbor#160]
Steps to reproduce:
- Create fresh docker image (preferably with a detector enabled, such as the face detector)
- Open the console for the docker image
- Run `pip list`
- numpy version is latest (2.0.0 when I wrote this) instead of a `1.x` version [requested by thumbor](https://github.com/thumbor/thumbor/blob/252c5b10ff4766b8a09e0a017a11cb9912bf557a/setup.py#L55).

This is causing the face detector to crash and likely causes any local detector to crash. I can workaround by running `pip install` in the container but it would be good to update the image to read the setup file.

**Comment by NotWoods** [comment]
I gave it a shot! I'm a bit unfamiliar with requirements vs setup but I think I came up with a good solution.

**Comment by gingerlime** [comment]
Great stuff! It's merged and should push a new image to ghcr soon.
