### ISSUE TITLE
smart Feature Throws ModuleNotFoundError: No module named 'tc_redis'

### ISSUE THREAD

**Issue by ItsReddi** [MinimalCompact/thumbor#164]
When using the `/smart/` feature, the following error occurs:

```
ModuleNotFoundError: No module named 'tc_redis'
```

This indicates that the `tc_redis` package is missing. As a user, I expect the `smart` cropping feature to work without needing to install additional dependencies manually.

#### Steps to Reproduce:
1. Run Thumbor with `/smart/` in the URL.
2. Observe the `ModuleNotFoundError` for `tc_redis`.

#### Expected Behavior:
The `/smart/` feature should work without additional package installations.

**Comment by kusmierz** [comment]
I guess I solved it in https://github.com/MinimalCompact/thumbor/pull/165
