### ISSUE TITLE
How much memory is enough to work properly

### ISSUE THREAD

**Issue by singhravi1** [MinimalCompact/thumbor#22]
Hello guys,

I'm talking about the multiprocessing docker container here.
I checked the memory used by docker container while only running without any processing and it was **taking ~400 MB** of memory.
My concern is, how much memory should i reserve for the container for running without any problem if i'm aiming more than **1000 requests/sec** and assuming **images to be of size less than 10 MB**?

Thanks

**Comment by gingerlime** [comment]
Memory footprint depends on the number of processes you choose.

1000 req/sec sounds like a lot to me!

see https://github.com/thumbor/thumbor/issues/1053 and https://github.com/thumbor/thumbor/issues/1144

(and maybe also #14)

**Comment by gingerlime** [comment]
Closing for now. Feel free to re-open if you have any further questions or suggestions.
