### ISSUE TITLE
Getting error while running thumbor in kubernetes

### ISSUE THREAD

**Issue by hemantaltair** [MinimalCompact/thumbor#23]
root@thumbor-qa-5df6d9845c-54kpg:~# /docker-entrypoint.sh circus
---> Starting thumbor solo...
usage: server.py [-h] [--version] [-p PORT] [-i IP] [-f FD] [-c CONF]
                 [-k KEYFILE] [-l LOG_LEVEL] [-a APP] [-d]
                 [--use-environment USE_ENVIRONMENT]
server.py: error: argument -p/--port: invalid int value: 'tcp://100.69.107.104:80'

**Comment by gingerlime** [comment]
I don't have hands-on experience with Kubernetes unfortunately, but there's an [example recipe](https://github.com/MinimalCompact/thumbor/tree/master/recipes/kubernetes) that might help? Any contributions to those recipes would be welcome. See #1 and #15

**Comment by hemantaltair** [comment]
This issue I resolved by running the command -  thumbor

**Comment by gingerlime** [comment]
That's good to know. If you can contribute something to the readme or the recipe, it would be great. Please note that you might prefer to run thumbor with more than one process, but perhaps with K8s you just create as many replicas as necessary. Also caching can provide very considerable performance boost and you might want to consider it. If you can contribute there for making local caching works with K8s it would be much appreciated as well.

Closing this for now.

**Comment by liorkleinman** [comment]
> This issue I resolved by running the command - thumbor

Just encountered with the same issue
Can you place explain more about your solution?

**Comment by jnm733** [comment]
> This issue I resolved by running the command - thumbor

Hi! I have now the same error. Can you tell me where do you run the command to solve it?

I have checked that the error only appears when the Service is created before the Deployment.
