### ISSUE TITLE
how to disable local (result/loader) storage

### ISSUE THREAD

**Issue by ivanmarchenko83** [MinimalCompact/thumbor#29]
Hi,

i run it like this:
`docker run -p 80:80 -e MAX_AGE=0 -e STORAGE_EXPIRATION_SECONDS=0 -e IGNORE_SMART_ERRORS='True' -e THUMBOR_NUM_PROCESSES=2 -e ALLOW_UNSAFE_URL='False' -e SECURITY_KEY='{my-secret-key-here}' -v /tmp/docker-data:/data --restart always -d minimalcompact/thumbor`

folder /tmp/docker-data is getting polluted with files, nothing is removed. So i had to create cron task which drops everything out of there.

if i run it without `-v /tmp/docker-data:/data` - docker volume takes all available space and host dies.

pretty sure that in original thumbor `STORAGE_EXPIRATION_SECONDS=0` - should force it to remove all temp files as soon as they served.

have no need in any kind of cache inside of thumbor because we have multiple caching layers in front of it and thumbor is the last stage.

Please let me know if you need anything else from me.

Thank you for creating this great image!

**Comment by kkopachev** [comment]
use `-e RESULT_STORAGE='thumbor.result_storages.no_storage'` to disable result storage. 
Same with `-e STORAGE='thumbor.storages.no_storage'` to disable loader storage

**Comment by ivanmarchenko83** [comment]
Looks like it works exactly as i need it. Thanks for your help!
