### ISSUE TITLE
/var/lib/docker/overlay2 - takes all  available space

### ISSUE THREAD

**Issue by ivanmarchenko83** [MinimalCompact/thumbor#30]
everything looked good at the beginning than everything collapsed.

running container like this:

`sudo docker run -p 80:80 -e MAX_AGE=0  -e RESULT_STORAGE='thumbor.result_storages.no_storage' -e STORAGE='thumbor.storages.no_storage' -e STORAGE_EXPIRATION_SECONDS=0 -e IGNORE_SMART_ERRORS='True' -e THUMBOR_NUM_PROCESSES=2 -e ALLOW_UNSAFE_URL='False' -e SECURITY_KEY='{my secret key}' /tmp/docker-data:/data --restart always -d minimalcompact/thumbor`

in less than a day `/var/lib/docker/overlay2` consumed 11G. Not that many requests, i would say less than 1 request in a second.

was able to reclaim all space only after i've removed container and did `docker system prune -a`

please let me know if need more info

**Comment by gingerlime** [comment]
Can you check which specific files are added to this folder and whether they're related to your thumbor (or maybe other containers or left-overs from old images)? I'm running thumbor with docker for months without any issues (albeit, I do use cache, and I think it's actually invaluable, even if you have other caching layers)... 

You can also try `docker system prune -a` perhaps to clean things up and start again and see if it's really thumbor that's taking the space.

**Comment by ivanmarchenko83** [comment]
from what i can see whole space is consumed by docker /tmp folder which is full of files like:
-rw------- 1 root root  35850208 Jun 29 09:56 tmpTmPuhN
-rw------- 1 root root  35850208 Jun 29 09:03 tmpUHqCbR
-rw------- 1 root root  35850208 Jun 29 09:56 tmpUSbi4t
-rw------- 1 root root  35850208 Jun 29 09:52 tmpUpJcdO
-rw------- 1 root root  35850208 Jun 29 09:15 tmpVo7hR4
-rw------- 1 root root  35850208 Jun 29 09:47 tmpWUfqlM
-rw------- 1 root root  35850208 Jun 29 09:48 tmpYD8vzT
-rw------- 1 root root  35850208 Jun 29 09:07 tmpYVQcT9
-rw------- 1 root root  35850208 Jun 29 09:39 tmpZQ95LB
and so on

**Comment by ivanmarchenko83** [comment]
i would guess it is because i am running it with `thumbor.result_storages.no_storage` and `thumbor.storages.no_storage`.
probably thumbor just using system temp files as a place for temp data.
as of now going to map it to host /tmp/subfoder so i can clean it with cron...

**Comment by gingerlime** [comment]
Sounds like a good workaround. I do use storage, but still clean it up from time to time using a fairly simple cron job. Something like this:

```bash
# will clean-up any file not accessed for more than 24 hours
docker-compose exec thumbor bash -c 'find /data -type f -amin +1440 -delete'
```

**Comment by gingerlime** [comment]
I'll close this for now, but if you still have any questions, we're always happy to help :)
