### ISSUE TITLE
remotecv didn't support tc_aws?

### ISSUE THREAD

**Issue by clyquan** [MinimalCompact/thumbor#32]
Hi, I want to know if the remotecv support tc_aws, such as minio. According to the requiresments, I didn't find the tc_aws related infomation.

**Comment by gingerlime** [comment]
It should be available. The removecv docker image is based on the thumbor image, which has tc_aws installed. See https://github.com/MinimalCompact/thumbor/blob/5f50ccdfed53179d25bc59ed33f42f9e9959ee2d/thumbor/requirements.txt#L12

**Comment by clyquan** [comment]
I set up a docker stack according to your configuration, but didn't find the remotecv container get any request even if the LOG_LEVEL=debug.

**Comment by gingerlime** [comment]
@clyquan did you check out the recipe at https://github.com/MinimalCompact/thumbor/tree/master/recipes/docker-compose/remotecv ?

I'm not actively using remotecv myself, so I'm not sure if I can be of much help unfortunately... But maybe others know?

Let me know if you have a more specific problem / error or if you can share what you're doing precisely. I'll re-open this for now

**Comment by clyquan** [comment]
@gingerlime , I make it work now, and there were two issues in my past test.

- use LOADER, instead of REMOTECV_LOADER;

- the remotecv_aws.loader didn't support TC_AWS_ENPOINT, TC_AWS_*, now I fork remotecv_aws and add these support

Now , the smart crop work well.

**Comment by gingerlime** [comment]
Would you be interested to submit a PR with the changes?

**Comment by clyquan** [comment]
OK, I will submit, thanks a lot.

**Comment by r0bdiabl0** [comment]
I am seeing this issue now using TC_AWS. @clyquan I don't see your PR with the changes. @gingerlime Here is his forked project updating remotely_aws: https://github.com/clyquan/remotecv_aws
