### ISSUE TITLE
Adding additional plugins (tc_prometheus)

### ISSUE THREAD

**Issue by lenzls** [MinimalCompact/thumbor#34]
Hello,

is it somehow possible to easily add additional plugins to thumbor running in this image?

I want to use [tc_prometheus](https://thumbor.readthedocs.io/en/latest/plugins.html#thumbor-prometheus-by-simon-effenberg) but it does not seem to be included.

regards,

Simon

**Comment by gingerlime** [comment]
Hi Simon,

I'm generally open to adding popular plugins to the base image, as long as they don't over-inflate the image size, memory footprint etc (when unused, by default). I'm not familiar with this particular plugin though.

If you want to DIY it though, it should generally be quite simple. Basically create a new image based on `minimalcompact/thumbor`.

As an example, see how the `remotecv` is set-up: https://github.com/MinimalCompact/thumbor/tree/master/remotecv, so I imagine you can do something very similar that `pip install`s what you need, plus modifies the `docker-entrypoint.sh` to get the env variables you need (if you need it, you might be able to use it without modifying it, and just pass the variables you need (which would be available to thumbor anyway)

Let me know if you need help. Otherwise, if you can test it out and see whether it's generally safe to add this plugin. If it is, then I'm happy to merge a PR that adds it.

**Comment by lenzls** [comment]
Thanks for the link!

It seems like in this case, it is even just pip-installing a new package and that's it.

The only thing missing is some thumbor configuration via environment variables.

I'll try it out and will get back to you

**Comment by lenzls** [comment]
Okay, I did some tests today.

Here is a simple Dockerfile on top of the MinimalCompact Image:
https://github.com/lenzls/thumbor/blob/master/thumbor-with-metrics/Dockerfile

Just run the container with `METRICS=tc_prometheus.metrics.prometheus_metrics` as an environment variable and the prometheus endpoint will be exposed at http://localhost:8000.

The image size (according to `docker inspect`) increased from

        "Size": 1694830812,
        "VirtualSize": 1694830812,

to 

        "Size": 1695120715,
        "VirtualSize": 1695120715,

Although I have not so much experience, so I'm not sure if this a sensible metric or what else I could test.

I don't have a big production setup running, so I can't give you a lot of creditable performance hints.

Let me know if I can do something else

**Comment by gingerlime** [comment]
Thanks Simon, that's already very useful.

I guess you'd be able to use your own Dockerfile and use it, right?

I'm not sure which plugins should be included with the base image and which should be left out to be honest. I would imagine it's worth having popular plugins?

As far as I can tell, the size difference is pretty negligible, and the way the thumbor importers work, it looks like it won't load anything unless you actively set the `METRICS` param anyway, so the impact of including it with the base is pretty small.

I guess it's mostly a question of how many people actually need this? @kkopachev what do you think?

**Comment by lenzls** [comment]
> I guess you'd be able to use your own Dockerfile and use it, right?

For now yes.

I published my image here in case someone needs it https://hub.docker.com/r/enteente/thumbor-with-prometheus-metrics until the plugin eventually gets into the main image.

**Comment by kkopachev** [comment]
I think we can include that one, since it has little footprint and not automatically loaded.

However, I'd rather figure out a way for easier extension of existing image. It's not problem creating new docker file with `pip install blah` in it, but then there is no easy way (or I don't know about it) on how to extend config file easily. Right now I have to copy existing file content to my local, add new config vars and then use `ADD` command to include it in my image. And it's painful to keep track of upstream changes to config file.

**Comment by gingerlime** [comment]
@kkopachev thank you!

If you need to bring your own config, you don't necessarily need to create your own image. You can also mount the config file via docker volumes, e.g. `docker run -p 80:80 --volume /path/to/thumbor.conf:/app/thumbor.conf:ro minimalcompact/thumbor`. But I still think I agree with you, at the very least being able to automatically map envs to thumbor. see https://github.com/MinimalCompact/thumbor/issues/4#issuecomment-412423989 for example...

If you have any ideas to improve things, let me know :)

Until then, @lenzls would you mind creating a PR to add this plugin to the baseline?

**Comment by lenzls** [comment]
Sure @gingerlime 

But I'm having trouble even building the current masters Dockerfile on my machine.

I'm always greeted by

```
[18:11:11] simon@iguana:~/dev/thumbor/thumbor  ((dfe8009...))--
[0] $> docker build . -t thumbor-vanilla:test
Sending build context to Docker daemon  38.91kB
Step 1/23 : FROM python:2
 ---> 3edf9092825f
Step 2/23 : LABEL maintainer="MinimalCompact"
 ---> Using cache
 ---> 84bd674dbcb3
Step 3/23 : VOLUME /data
 ---> Using cache
 ---> e9358b521ce1
Step 4/23 : RUN      awk '$1 ~ "^deb" { $3 = $3 "-backports"; print; exit }' /etc/apt/sources.list > /etc/apt/sources.list.d/backports.list &&     apt-get update &&     apt-get -y upgrade &&     apt-get -y autoremove &&     apt-get install -y -q         python-numpy         python-opencv         git         curl         libdc1394-22         libjpeg-turbo-progs         graphicsmagick         libgraphicsmagick++3         libgraphicsmagick++1-dev         libgraphicsmagick-q16-3         zlib1g-dev         libboost-python-dev         libmemcached-dev         gifsicle=1.88*         ffmpeg &&     apt-get clean
 ---> Running in 850569ccdf49
Get:1 http://security.debian.org/debian-security buster/updates InRelease [39.1 kB]
Get:2 http://deb.debian.org/debian buster InRelease [118 kB]
Get:3 http://deb.debian.org/debian buster-updates InRelease [46.8 kB]
Get:4 http://deb.debian.org/debian buster-backports InRelease [44.1 kB]
Get:5 http://security.debian.org/debian-security buster/updates/main amd64 Packages [49.4 kB]
Get:6 http://deb.debian.org/debian buster/main amd64 Packages [7897 kB]
Get:7 http://deb.debian.org/debian buster-backports/main amd64 Packages [12.9 kB]
Fetched 8207 kB in 4s (2012 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
Calculating upgrade...
The following packages will be upgraded:
  linux-libc-dev
1 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 1185 kB of archives.
After this operation, 0 B of additional disk space will be used.
Get:1 http://security.debian.org/debian-security buster/updates/main amd64 linux-libc-dev amd64 4.19.37-5+deb10u1 [1185 kB]
debconf: delaying package configuration, since apt-utils is not installed
Fetched 1185 kB in 0s (2969 kB/s)
(Reading database ... 24544 files and directories currently installed.)
Preparing to unpack .../linux-libc-dev_4.19.37-5+deb10u1_amd64.deb ...
Unpacking linux-libc-dev:amd64 (4.19.37-5+deb10u1) over (4.19.37-5) ...
Setting up linux-libc-dev:amd64 (4.19.37-5+deb10u1) ...
Reading package lists...
Building dependency tree...
Reading state information...
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Reading package lists...
Building dependency tree...
Reading state information...
E: Version '1.88*' for 'gifsicle' was not found
The command '/bin/sh -c awk '$1 ~ "^deb" { $3 = $3 "-backports"; print; exit }' /etc/apt/sources.list > /etc/apt/sources.list.d/backports.list &&     apt-get update &&     apt-get -y upgrade &&     apt-get -y autoremove &&     apt-get install -y -q         python-numpy         python-opencv         git         curl         libdc1394-22         libjpeg-turbo-progs         graphicsmagick         libgraphicsmagick++3         libgraphicsmagick++1-dev         libgraphicsmagick-q16-3         zlib1g-dev         libboost-python-dev         libmemcached-dev         gifsicle=1.88*         ffmpeg &&     apt-get clean' returned a non-zero code: 100

```

Do you have an idea what goes wrong there?

**Comment by gingerlime** [comment]
Thanks @lenzls ... I didn't build manually for a while, but I think the automated build actually failed (silently?) with a similar error. I'll take a look when I get a chance...

**Comment by gingerlime** [comment]
@lenzls I just pushed a small commit that should hopefully fix this (waiting for the build to run, which takes time...)

**Comment by gingerlime** [comment]
hmm... I think there's another problem now, so it might take a while longer to debug this. Docker builds aren't entirely reproducible sadly when things move forward, but hope I can work out those kinks.
