### ISSUE TITLE
3Gi is not enough for single process, keep getting OOMKilled from my kube 

### ISSUE THREAD

**Issue by ivanmarchenko83** [MinimalCompact/thumbor#35]
Hi,
running you image in kube cluster, it works great until it doesn't.
not that many request per second. but some of them are gifs. here is my configuration.
```
- name: STORAGE_EXPIRATION_SECONDS
            value: "60"
          - name: IGNORE_SMART_ERRORS
            value: "True"
          - name: THUMBOR_NUM_PROCESSES
            value: "1"
          - name: ALLOW_UNSAFE_URL
            value: "False"
          - name: SECURITY_KEY
            value: ".........................."
```

**is there a way to let thumbor know what is system maximum memory limit?**
because i've set on kube config limit 3Gb but the only thing cluster can do is to recycle pod.
thus i have 25 restarts over night....

i've experienced same problem with mongodb a while ago. the solution was to let mongodb know engine how much memory is the maximum available memory in system. Because apparently it only can fetch cluster memory limit but not the pod limit.

p.s. eventually recycled pod able to handle heavy request without eating that much memory. so it is possible. but i wasn't able to find any memory related env var in thumbor config...

**Comment by gingerlime** [comment]
Hi @ivanmarchenko83. I'm not that familiar with Kubernetes unfortunately... Do you run multiple instances / replicas of this pod? one thing that jumped out to me is that you use only one thumbor process. It's definitely possible to let docker/kubernetes handle replication for you, but you would definitely benefit from more processes. Basically something between 1-2x cpu cores is advisable (see #14). I'm not sure, but maybe thumbor multiprocess can handle killing hanging processes internally better? it's worth a shot in my opinion.

**Comment by ivanmarchenko83** [comment]
Thanks, going definitely to try multiprocess - didn't think that multiprocess works in different way then single thread.
in my case kubernetest is just a way tor manage/scale-up/scale-down multiple docker instances (called pods) on few real ec2 (called nodes).

cahcing wise - in my case kube with thumbor pods inside is that last stage after all caching layers we have. so basically it is going to be called only if requested file wasn't found on permanent storage layer.

overall i am pretty happy with perfomance so 60 seconds is just in case if same new resource going to be requested in parallel while first is still generating.

**Comment by gingerlime** [comment]
Yes, we also use external caching with cloudflare, but at least there, if you reach an edge that doesn't have the image cached, it would hit your thumbor, and that's where a local cache is good to have. If your caching layers are relatively "close" then you should be fine... I just don't know what's your setup like. 60 seconds seems very low though.

In terms of scaling, if you define enough replication on Kubernetes, then you should be fine. I still run thumbor in multiprocess and let it handle it, and it does a fine job at it (with little overhead). It's worth trying anyway :)

Can't really say much about memory usage. Mine is on the low side, but we don't have many gifs.

**Comment by ivanmarchenko83** [comment]
so i see that in 6.5h and no even single restart - which means it is definitely works better with memory when thumbor runs in 2 process mode per docker instance
```
   - name: THUMBOR_NUM_PROCESSES
      value: "2"
```

probably it should be mentioned somewhere that thumbor is no very stable when it works as single process...

Thanks for you help!

**Comment by gingerlime** [comment]
That's good to know. Why only 2 processes? If you have more CPU cores then I would recommend matching the number of cores or even more ~1.5-2x

> probably it should be mentioned somewhere that thumbor is no very stable when it works as single process...

It's really hard to know for sure what's going on without a lot more details about your particular setup and types of images. You can report this upstream to [thumbor](https://github.com/thumbor/thumbor) though. Perhaps @kkopachev is best to comment on it, but intuitively I would say that this isn't universally true and thumbor itself should be fairly stable. There's no magic with multiprocess, it simply spins more thumbor processes and manages them using [circus](https://pypi.org/project/circus/) ...
