### ISSUE TITLE
Template Quoting

### ISSUE THREAD

**Issue by shaneog** [MinimalCompact/thumbor#4]
I'm currently setting up this image with Kubernetes, and have run into some issues.

Are there any reasons why there is a differing approach to quoting the environment variables in the template file? 
Some are quoted, e.g. `METRICS` and some are not, e.g. `TC_AWS_ENDPOINT`.

Would you accept a PR "fixing" the broken ones? This is causing me no end of headaches trying to pass environment variables.

**Comment by gingerlime** [comment]
> I'm currently setting up this image with Kubernetes

Would you be able to share your setup, and maybe contribute to #1 ?

> Are there any reasons why there is a differing approach to quoting the environment variables in the template file?
Some are quoted, e.g. METRICS and some are not, e.g. TC_AWS_ENDPOINT.

I'm glad you bring this up. I was wondering about it as well :) The original config was based on APSL/docker-thumbor, and I didn't dig too deep into it, but definitely bumped into a problem indirectly related to it recently on efdee768134e7951630d8fb9a0d9bcbf2a534399

I was actually trying to avoid this mapping entirely, and just pass any env variables passed to docker directly into the thumbor config, but couldn't work out a generic way to do this that would also deal with all types of values, i.e. strings, ints, booleans, arrays, etc. Some of the config keys would accept `None`, `True`, or a number ... whilst others are expecting a string, and some might expect either a `None` or a string... So not sure how to deal with this in a clean/generic way. I was hoping to spend more time looking into this, but didn't get round to it yet.

> Would you accept a PR "fixing" the broken ones? This is causing me no end of headaches trying to pass environment variables.

Absolutely. See my comment above. Ideally, I'm hoping to find a solution that would not hard-code any settings, but simply pass over any environment value to the thumbor config. But failing that, fixing the basic config and tidying it up somehow would be great. I also wish to find a way to make sure this is kept in-sync with the thumbor config. Maybe even loading the thumbor [config code](https://github.com/thumbor/thumbor/blob/master/thumbor/config.py) to parse any env values and then set them??

...just throwing some ideas, but I'm definitely interested in improving this.

**Comment by shaneog** [comment]
I’ll defintely contribute the Kubernetes manifests once I’ve made it work. 

I think deciding what to do about the configuration is going to be very important for the future. 
For example, my earlier PR adding the thumbor-cloud-storage plug-in should have added environment variables to the configuration, but I didn’t realize that at the time (I will add another PR shortly). 
 
So, we can either try to deal with all variables in the conf template _or_ allow the user to mount a configuration file themselves. 
Would you be interested in an option for this?

**Comment by gingerlime** [comment]
You can already provide your own `thumbor.conf` file, but it's a bit of a hack compared to the standard setup. i.e. you can do

```shell
docker run -p 80:80 --volume /path/to/thumbor.conf:/app/thumbor.conf:ro minimalcompact/thumbor
```

I still think it's easier and more docker-friendly to let people override any of the default thumbor config by passing those to docker via `env` or some other obvious way. Maybe a nicer override for providing your own config is also a good idea, to avoid this `:ro` hack above

**Comment by shaneog** [comment]
After having looked into this a bit more, the way the variables are interpreted now seems to be to avoid lots of  `if defined` checks in the template, and thus it requires that certain variables are provided quoted, and some not.
Quite confusing.

This completely breaks providing _some_ variables directly in Kubernetes manifests, since YAML un/quoting works differently.

Example, providing a `STATSD_HOST` with the IP of the Kubernetes host just doesn't work..
```yaml
        env:
        - name: STATSD_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
```

I am not familiar with _all_ of the configuration used in the template, but I can make a PR which is a lot more verbose and contains some `if defined` checks, but should work. How about that?

**Comment by shaneog** [comment]
I have this running in production on Kubernetes right now 🎉 

I will share my manifests once I've finished #6 because right now I am overwriting the template file via ConfigMap, and this will be pointless after that PR is merged.

**Comment by gingerlime** [comment]
Thanks again, @shaneog. This is definitely a possibility. I wonder if there's a way to generalise it though to fit *any* variable you pass to it, without hard-coding explicit config directives... something like (psudo-code)

```jinja
{% for k,v in ENV %}
{% if v is string %} {{ k }} = "{{ v }}"
{% else %} {{ k }} = {{ v }}
{% endif %}
```

I tried it out a bit a couple of weeks ago, but somehow couldn't make it work properly, but I hope it's possible. Then there's no hard-coding at all, and anything you pass via ENV or configmaps would map into your thumbor config.

**Comment by shaneog** [comment]
This would bring many unnecessary variables into the configuration, unless you prefixed everything so that they can be identified. (e.g. `THUMBOR_STATSD_HOST` instead of `STATSD_HOST`)

For example, Kubernetes pods have environment variables automatically declared for all services and ports in the cluster - so the ENV can get quite large.

**Comment by gingerlime** [comment]
Assuming it can work, then yes, the config will get "polluted" with some unrelated variables, but I think it's still better than having to define all possible config variables up front, and thumbor should basically ignore any config directives that don't concern it anyway. So I would still say it's a better approach (if we can get it to work, but I'm not sure how exactly yet).

**Comment by gingerlime** [comment]
Hey @shaneog do you plan to continue working on this? I'd be happy to help.

Otherwise, if you could you contribute your kubernetes configs to #1, I would really appreciate it.

**Comment by gingerlime** [comment]
PR was merged. Thanks for your contribution, @shaneog
