### ISSUE TITLE
nginx proxy - result_storage directory for auto webp images

### ISSUE THREAD

**Issue by limuhob** [MinimalCompact/thumbor#40]
Hi,

I'm trying MinimalCompact/thumbor container with tag 6.7.0 and It seems to me that nginx_proxy uses bad direcotry for webp (auto) images. It uses result_storage/webp but should be result_storage/auto_webp.  

https://github.com/MinimalCompact/thumbor/blob/05f1d554102cbe1719f98e57a8d2498749954d32/nginx-proxy/nginx.tmpl#L12

vs

https://github.com/thumbor/thumbor/blob/ad8d3813bcd6875b890e43c1c39955d6a47b2c22/thumbor/result_storages/file_storage.py#L101

**Comment by gingerlime** [comment]
Thanks for reporting this @limuhob. I think you're right and it was changed in https://github.com/thumbor/thumbor/commit/8b550f55ed10ebacadb8bf6ed624c3c400672746#diff-fe10cb3160bddcc7d9263fd49d508b0eL71

Would you be interested submitting a PR to fix this?

**Comment by limuhob** [comment]
I will try it.
