### ISSUE TITLE
AUTO_PNG_TO_JPG cannot be configured

### ISSUE THREAD

**Issue by tobias-tsf** [MinimalCompact/thumbor#41]
Hi! Just noticed the AUTO_PNG_TO_JPG configuration variable cannot be set via environment variable. Seems like thumbor added it a while ago, but it never made it to the image.

See: https://thumbor.readthedocs.io/en/latest/configuration.html#auto-png-to-jpg

Any chance this could be added? Or was it removed on purpose?

I checked https://github.com/MinimalCompact/thumbor/blob/master/thumbor/conf/thumbor.conf.tpl

AUTO_WEBP is in there, but not AUTO_PNG_TO_JPG.

Thanks a lot!

**Comment by gingerlime** [comment]
Hi @tobias-tsf. Thanks for reporting this. Do you want to submit a PR for it?

related #39

**Comment by tobias-tsf** [comment]
Hey @gingerlime.

Done -> https://github.com/MinimalCompact/thumbor/pull/43.

Thanks for the quick reply!
