### ISSUE TITLE
creating more tests

### ISSUE THREAD

**Issue by gingerlime** [MinimalCompact/thumbor#50]
I recently created some [simple tests to cover nginx-proxy caching](https://github.com/MinimalCompact/thumbor/blob/b1dc1863aaba0bc74674f0d64ffbaea23a0c4675/tests/nginx-proxy.bats) (#47) using [bats-core](https://github.com/bats-core), and [integrated them](https://github.com/MinimalCompact/thumbor/blob/b1dc1863aaba0bc74674f0d64ffbaea23a0c4675/.semaphore/semaphore.yml) into the automated build/test/push process on Semaphore 2.0.

Probably makes sense to write a few more tests to cover common scenarios, but not sure exactly what should be tested (it doesn't make sense to duplicate tests that thumbor core is doing, so focus only on the docker images)

**Comment by gingerlime** [comment]
@kkopachev can you suggest some things we could/should test and how to test them?

**Comment by kkopachev** [comment]
:man_shrugging: 
Not sure if there are anything which deserves testing. 
nginx-proxy should just be [replaced with nginx caching](#54).

**Comment by gingerlime** [comment]
Thanks @kkopachev. Yes, you're probably right. I think I realized while writing tests that they are mostly related to nginx proxy caching. If we replace it with nginx built-in caching there's much less to test. Still probably a few things like AUTO_WEBP and correct headers might be worth testing, but it's still either testing nginx or thumbor, both projects have their own tests :)

I'll close this for now!
