### ISSUE TITLE
Upgrade boto dependency

### ISSUE THREAD

**Issue by ballad89** [MinimalCompact/thumbor#57]
Hello

I am running this container on EKS (Amazon Kubernetes) and it now lets you access credentials via a web token as documented here https://boto3.amazonaws.com/v1/documentation/api/latest/guide/configuration.html#assume-role-with-web-identity-provider

In order to use it, the python sdk needs to be upgraded to at least a version listed here
https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts-minimum-sdk.html

**Comment by gingerlime** [comment]
Thank you @ballad89. Would you be interested creating a PR for this?
