### ISSUE TITLE
Custom loader

### ISSUE THREAD

**Issue by HZ-labs** [MinimalCompact/thumbor#60]
How can I add a custom image loader?

**Comment by gingerlime** [comment]
HI @HZ-labs which custom image loader are you interested in adding/using?

In general, you can create your own docker image based on this one, and add anything you need. If there's something that others might benefit from, then we're generally open to accept PRs or we might be able to help. (e.g. see #34)

**Comment by HZ-labs** [comment]
Thank you, I would like adding/using loader which can convert base64 encoded url to normal.

**Comment by gingerlime** [comment]
Is this something you created? or is there one (open-source/public) already?

**Comment by HZ-labs** [comment]
I did not find loader as I needed. I will try to create myself

**Comment by HZ-labs** [comment]
Done! https://github.com/HZ-labs/thumbor-base64-loader
