### ISSUE TITLE
CloudFront or other CDN solution when using remotecv

### ISSUE THREAD

**Issue by csheppard** [MinimalCompact/thumbor#62]
So, I've got nginx-proxy-cache, thumbor and remotecv set up with images only loaded from S3.

As I understand so far, using smart crop will return the image immediately with a basic crop and nginx will not cache the result while remotecv works away.

Upon reload, thumbor will smart crop the image and nginx will cache the result this time.

What if I want to put CloudFront at the top of the stack? It will cache the first unsmart image. 

Can I get nginx to pass on the no cache headers from the first request?

**Comment by gingerlime** [comment]
I'm not using remotecv, but just did a quick test and as far as I can tell it behaves as expected:

The first request will return a response *without* `Cache-Control` header. Something like this:

```
HTTP/1.1 200 OK
Server: nginx/1.17.3
Date: Sun, 15 Dec 2019 12:41:42 GMT
Content-Type: image/png
Content-Length: 9722
Connection: keep-alive
Vary: Accept
Etag: "8ae3f09e5245b09f157a48e842e181e9612edb2a"
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true
Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS
Access-Control-Allow-Headers: Accept,Authorization,Cache-Control,Content-Type,DNT,If-Modified-Since,Keep-Alive,Origin,User-Agent,X-Mx-ReqToken,X-Requested-With
```

The second request, after remotecv did the smart cropping, *will* contain a `Cache-Control` header. It would look something like this:

```
HTTP/1.1 200 OK
Server: nginx/1.17.3
Date: Sun, 15 Dec 2019 12:42:04 GMT
Content-Type: image/png
Content-Length: 17457
Connection: keep-alive
Expires: Mon, 16 Dec 2019 12:42:04 GMT
Vary: Accept
Etag: "20eb77c17547f244b0af621f93a2cb239e19d432"
Cache-Control: max-age=86400,public
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true
Access-Control-Allow-Methods: GET, POST, PUT, DELETE, OPTIONS
Access-Control-Allow-Headers: Accept,Authorization,Cache-Control,Content-Type,DNT,If-Modified-Since,Keep-Alive,Origin,User-Agent,X-Mx-ReqToken,X-Requested-With
```

So as long as your CDN respects cache headers and doesn't cache unless the header exists, you should be fine. I'm not sure how Cloudfront deals with missing `Cache-Control` headers. I guess it would be better if thumbor returned an explicit `Cache-control: private, max-age=0, no-cache` or something similar on the first request, to indicate that it definitely shouldn't be cached. This is something to ask the thumbor project however?

Hope this helps!

**Comment by csheppard** [comment]
Ah great, thanks! I didn't think about how it would handle the missing `Cache-Control` header, I will look into it.
