### ISSUE TITLE
Add more optimizer plugins

### ISSUE THREAD

**Issue by alexandernst** [MinimalCompact/thumbor#64]
This repo seems to have a nice collection of optimizer plugins: https://github.com/thumbor/thumbor-plugins

**Comment by gingerlime** [comment]
@kkopachev any thoughts whether we should include any/all by default?

**Comment by kkopachev** [comment]
I don't have solid opinion here. It's nice to have them in image, but then user have to opt-in in config to use them. On the other hand it's just one-line addition to Dockerfile and anyone can do that themselves. 
I am leaning towards pip-installing them, and mention in readme.

**Comment by alexandernst** [comment]
Please note that the plugins will need the required 3rd party apps (optipng, pngcrush and so on...). Those should be added to the Dockerfile as well as some of them are not available in the repos.

**Comment by kkopachev** [comment]
Oh, right. That too. That might be challenging.
Then maybe users should install plugins and apps they need. Some of optimizers counteract each other (imgmig/mozjpeg), some might be redundant (mozjpeg). 
:man_shrugging:

**Comment by alexandernst** [comment]
I ended up exposing the binaries from the host to the container via volumes. That might be an alternative solution.

**Comment by kkopachev** [comment]
From my understanding, there is no guarantee it's gonna work that way. Missing libs and such.
Which optimizers do you use?

**Comment by alexandernst** [comment]
Yes, the binary would need to match the same libraries (check with `ldd`). Probably statically compiled binaries will be more helpful here. 

I use only optipng.

**Comment by kkopachev** [comment]
Well, not sure. Probably users should extend dockerfiles themselves as needed. Looks like too much trouble (maintenance) for quite narrow use case.

**Comment by gingerlime** [comment]
Thanks @kkopachev @alexandernst for sharing your thoughts and discussing this.

I think we'll opt out from adding extra plugins for the time being. The base image can be extended if necessary, and it seems like quite a few edge-cases that make it tricky to maintain. I'd keep our minds open though to re-evaluate in future if there are specific use-cases that are compelling.

If you guys don't mind, I'll close this for now, but if there's something worth discussing, feel free to re-open or create a new issue.
