### ISSUE TITLE
Using of single instance of thumbor

### ISSUE THREAD

**Issue by vicmosin** [MinimalCompact/thumbor#69]
Hi there, 
I want to migrate from APSL/docker-thumbor image and looking for a way of using instance of thumbor itself, without any additional features such as nginx-proxy-cache etc.. Is this possible to do it with this image without building your own? Tried so far to expose 8888 only but seems to not work.

Thanks in advance

**Comment by kkopachev** [comment]
How do you run it?
```
docker run -p 80:80 minimalcompact/thumbor
wget http://localhost/unsafe/500x150/i.imgur.com/Nfn80ck.png
```
should just work. By default it listens on port 80.

**Comment by vicmosin** [comment]
Mh.. Yeah, looks like it works, I guess the issue somewhere at my side. Thanks
