### ISSUE TITLE
Simple recipe doesn't load any detectors with image version 7.0.0a2

### ISSUE THREAD

**Issue by danbo** [MinimalCompact/thumbor#71]
... because there is an environment setting missing 

https://github.com/MinimalCompact/thumbor/blob/1d9d783661d2659ff416ef92ddc2b3d80aa8675e/recipes/docker-compose/simple/docker-compose.yml#L5

```
  - DETECTORS=['thumbor.detectors.face_detector','thumbor.detectors.feature_detector']
```

such as in the swarm example:

https://github.com/MinimalCompact/thumbor/blob/1d9d783661d2659ff416ef92ddc2b3d80aa8675e/recipes/docker-compose/swarm/docker-compose.yml#L27

See: https://thumbor.readthedocs.io/en/latest/enabling_detectors.html

**Comment by gingerlime** [comment]
Thanks for reporting @danbo. I just created a new PR for 7.0.0a5 but looking at this, I'm not sure if the simple recipe should care about detectors. It's deliberately simple and limited to simple use-cases. Also trying to keep docker-compose to a minimum, so it's more approachable to someone who's just starting.

So I think it's more-or-less deliberate... I'll close it but if you think I'm making a wrong decision, please let me know and happy to re-consider :)
