### ISSUE TITLE
Do you plan upgrade to 6.5.2

### ISSUE THREAD

**Issue by azhurbilo** [MinimalCompact/thumbor#8]
Thnx a lot for you docker image.
Do you plan upgrade to 6.5.2?

https://github.com/thumbor/thumbor/releases/tag/6.5.2

next change looks great

> Support Graceful shutdown on SIGTERM and SIGINT(@Globegitter)

**Comment by gingerlime** [comment]
Absolutely. Going to push 6.5.2 very soon :)
