### ISSUE TITLE
1.0-minimal-compact-4c9f8f4 cannot create an Image when using S3 Storage

### ISSUE THREAD

**Issue by liorkleinman** [MinimalCompact/thumbor#80]
Hi
I have been using apsl/Thumbor lastest Docker version with aws plugin (using S3 Storage), recently I updated version to tag: 1.0-minimal-compact-4c9f8f4 and now when running the same API calls I get:
POST returns 201 code, although I don't see the image being stored in S3 (worked in previous version)
GET returns 504, (NOT 404, meaning the server finds the image but cannot return it? Maybe connectivity problem?)

I believe the configuration should be fine (regarding connectivity to S3), since both API calls worked in previous version.

Configuration is added:

ALLOW_UNSAFE_URL False
AWS_ACCESS_KEY_ID MY_AWS_ACCESS_KEY
AWS_SECRET_ACCESS_KEY MY_AWS_SECRET_ACCESS_KEY
LOG_LEVEL warn
MAX_AGE 86400
STORAGE tc_aws.storages.s3_storage
TC_AWS_STORAGE_BUCKET MY_BUCKET
TC_AWS_STORAGE_ROOT_PATH path
UPLOAD_DELETE_ALLOWED True
UPLOAD_ENABLED True
UPLOAD_MAX_SIZE 9999999999999999
UPLOAD_PHOTO_STORAGE tc_aws.storages.s3_storage
UPLOAD_PUT_ALLOWED True

Added variables when testing new thumbor version:

RESULT_STORAGE tc_aws.result_storages.s3_storage
LOADER tc_aws.loaders.s3_loader
TC_AWS_LOADER_BUCKET vo-thumbor-bucket
TC_AWS_LOADER_ROOT_PATH path
TC_AWS_MAX_RETRY 5
TC_AWS_RESULT_STORAGE_BUCKET vo-thumbor-bucket
TC_AWS_RESULT_STORAGE_ROOT_PATH path

Any Ideas?
Thanks

**Comment by gingerlime** [comment]
APSL/thumbor isn't maintained as far as I'm aware. see https://github.com/APSL/docker-thumbor/issues/103

If you want, you can try with minimalcompact/thumbor and hope it works with it. Otherwise please feel free to re-open the issue. would be useful if you could provide a reproducible config (e.g. docker-compose.yml file or the docker command that you run with a sample image etc).

**Comment by liorkleinman** [comment]
Hi @gingerlime 
My issue refers to 1.0-minimal-compact-4c9f8f4 tag (not apsl/thumbor)
Coule you re-open?
Thanks
[thumbor.txt](https://github.com/MinimalCompact/thumbor/files/4793600/thumbor.txt)

**Comment by gingerlime** [comment]
Hi @liorkleinman I'm not familiar with this tag... can you find it on https://hub.docker.com/r/minimalcompact/thumbor/tags ?

**Comment by gingerlime** [comment]
Otherwise, it seems quite hard to reproduce your problem without further info ... logs etc (I don't have an environment to run your k8s config)

**Comment by liorkleinman** [comment]
Hi @gingerlime 
you are right - Double checked and In fact I am not sure what tag we are using but it was derived from the latest commit in the master branch of the project

**Comment by gingerlime** [comment]
Ok, hope this solved the problem for you. If not, then please try to reproduce this with a simple docker container or using docker-compose and post as many logs / details as possible to help us investigate this.
