### ISSUE TITLE
thumbor-nginx-proxy-cache returns a 503 - Service Unavailable

### ISSUE THREAD

**Issue by anshulmittal712** [MinimalCompact/thumbor#81]
I was trying this service for a project, and noticed the following:

1. `minimalcompact/thumbor` worked in the first go. I was able to resize and modify images. However, i wanted the service to be fronted by a NGINX caching layer.

2. I then tried `minimalcompact/thumbor-nginx-proxy-cache`. The command used was:
```
sudo docker run -p 8052:80 -v /var/run/docker.sock:/tmp/docker.sock:ro /home/anshul/temp_cache_dir:/var/cache/nginx minimalcompact/thumbor-nginx-proxy-cache
```

Here, the container starts, and accepts request at 8052, but I get an NGINX 503 Service Unavailable. Any obvious step that I'm missing, maybe?

I'm trying the example image from docs as follows:
```localhost:8052/unsafe/400x0/https%3A%2F%2Fgithub.com%2Fthumbor%2Fthumbor%2Fraw%2Fmaster%2Fexample.jpg```

and the startup logs are shown below:

![Thumbor NGINX](https://user-images.githubusercontent.com/8375454/86212006-e92fcf80-bb94-11ea-8540-9de9aa6cafc0.jpg)

Thanks.

**Comment by gingerlime** [comment]
@anshulmittal712 please check out the docker-compose recipes for more info about how to use nginx-proxy-cache with thumbor. Particulary important is the VIRTUAL_HOST settings. e.g. https://github.com/MinimalCompact/thumbor/blob/4c9f8f480a1e7230c36c6a9f7e42bc863f9f101e/recipes/docker-compose/simple/docker-compose.yml#L8

nginx-proxy-cache is based on https://github.com/nginx-proxy/nginx-proxy so you can find more info there
