### ISSUE TITLE
redis password support is incomplete

### ISSUE THREAD

**Issue by csheppard** [MinimalCompact/thumbor#86]
Using the REDIS_STORAGE_SERVER_PASSWORD and REDIS_QUEUE_SERVER_PASSWORD env variables results in NameError exceptions within thumbor.

I guess this is because they are not quoted in thumbor.conf.tpl?

I overcame this by using `REDIS_STORAGE_SERVER_PASSWORD="'mypassword'"`

But there is a fatal error with remotecv as no password is able to be passed via https://github.com/MinimalCompact/thumbor/blob/master/remotecv/docker-entrypoint.sh

It is supported though https://github.com/thumbor/remotecv/blob/master/remotecv/worker.py#L76

**Comment by gingerlime** [comment]
Thanks for reporting @csheppard. Are you able/willing to submit a PR to add the password param?

**Comment by csheppard** [comment]
Yea sure I could try a PR.

I'm not sure of the consequences of an empty string as the default password, e.g.
```REDIS_STORAGE_SERVER_PASSWORD = '{{ REDIS_STORAGE_SERVER_PASSWORD | default('') }}'```

So its probably best we do this?
```
{% if REDIS_STORAGE_SERVER_PASSWORD is defined %}
REDIS_STORAGE_SERVER_PASSWORD = '{{ REDIS_STORAGE_SERVER_PASSWORD }}'
{% else %}
REDIS_STORAGE_SERVER_PASSWORD = None
{% endif %}
```

**Comment by gingerlime** [comment]
Hi @csheppard I'm not sure you need to change the config, but rather than `docker-entrypoint` file. You can see an example: https://github.com/MinimalCompact/thumbor/blob/4c9f8f480a1e7230c36c6a9f7e42bc863f9f101e/thumbor/docker-entrypoint.sh#L13-L16

**Comment by gingerlime** [comment]
hey @csheppard are you able/interested submitting a PR for this?

**Comment by csheppard** [comment]
Sorry @gingerlime I'm short on time at the moment. I settled for not password protecting redis for now 😆

**Comment by gingerlime** [comment]
Seems reasonable for many cases actually (if redis lives in docker). I'll close this for now, although I think it can be a welcome change potentially in future.
