### ISSUE TITLE
Recipe for Thumbor Video Engine?

### ISSUE THREAD

**Issue by naomiaro** [MinimalCompact/thumbor#87]
Hello, I was hoping there would be a way to use this awesome docker image with The Atlantic's Video engine plugin

https://github.com/theatlantic/thumbor-video-engine

**Comment by gingerlime** [comment]
Hey @naomiaro. It sounds like you need to do two things to get it working:

1. create your own Dockerfile based on this one and install the video engine
2. Use a custom thumbor.conf file, so you can add the `ENGINE` setting on the Readme

So your Dockerfile will look something like this:

```Dockerfile
FROM minimalcompact/thumbor:latest

CMD pip install thumbor-video-engine
```

If you don't already have a `thumbor.conf` file, I guess best option is to grab the default one from the thumbor project? Then to use your own thumbor.conf file, you can simply mount it with docker, e.g.

`docker run -p 80:80 -v /path/to/your/thumbor.conf:/app/thumbor.conf minimalcompact/thumbor`

Hope this helps :)

**Comment by naomiaro** [comment]
Thanks! I think this plugin might need to wait until this issue is finished https://github.com/MinimalCompact/thumbor/issues/67

**Comment by gingerlime** [comment]
I hope so :) if there's anything I can do to help, please let me know! I'll close this for now, but feel free to re-open or open a new issue if necessary.
