### ISSUE TITLE
support metrics for multiple instances

### ISSUE THREAD

**Issue by frisi** [MinimalCompact/thumbor#92]
would be great to have a way to get metrics combined for several thumbor instances

iiuc this docker image starts several thumbor processes (8 by default) and exposes them on a single port using [circus](https://circus.readthedocs.io/en/latest/)

when setting the env variables
```
THUMBOR_NUM_PROCESSES: "2"
METRICS: "tc_prometheus.metrics.prometheus_metrics"
PROMETHEUS_SCRAPE_PORT: "15811"
```

one would expect to get combined metrics for these processes on port 15811.

## what really happens:

* the first thumbor starts the metrics server on port 15811 and logs to it
* the second instance complains about the port being in use and does not start metrics
* error log is cluttered with startup errors
* metrics only contain data for first instance

## proposal

A) warning message

* add a warning message to the documentation that metrics only work for NUM_PROCESSES=1

B) aggregated metrics

maybe we can find a way to support summed up metrics for thumbor:

it looks to me that https://github.com/thumbor-community/prometheus/ needs to be adapted (maybe @savar - developer of the prometheus metrics plugin - has an opinion on that)

everything that is stored within the `Metrics` object (`http_server_started` and `mappings`) would need to be placed into a shared storage
https://github.com/thumbor-community/prometheus/blob/master/tc_prometheus/metrics/prometheus_metrics.py#L25

this way only one server for metrics would be started, and all metric objects would increase the same counters

**Comment by gingerlime** [comment]
Thanks for the report @frisi. Have a look at #85. I'm not sure if there's a solution, but perhaps thumbor 7 will resolve it?

**Comment by frisi** [comment]
afaics thumbor 7 does not change the way metrics are provided. it simply imports a python module and calls the `incr` method
https://github.com/thumbor/thumbor/blob/173bff7d194a02d4bfab0338cbe9c5f94dbcd41d/thumbor/handlers/__init__.py#L84

if we want multiple thumbor processes to share the metrics we'll need a different metrics implementation that can share the counters between mutliple python processes (eg memcached/sqlite/nosql-dbs)

or we start a python server that does the counting and uses https://github.com/thumbor-community/prometheus/ internally (to expose the metrics) when starting circus.
and use a metrics implementation that communicates with this python server

**Comment by gingerlime** [comment]
@frisi this sounds like something to suggest to the core thumbor project perhaps?

**Comment by frisi** [comment]
not sure if the fact that multiple thumbor processes are exposed via a single port is specific to this project.

on other setups one knows the ports of the thumbor processes started, load balances them (eg nginx/haproxy) and monitors them separately.

MinimalCompact/thumbor hides this and just exposes a port for thumbor and one for metrics

**Comment by gingerlime** [comment]
You can always run multiple instances of the thumbor (or any) container, each one with only one process. You can see some benchmarks on #14. If I recall, in terms of performance this is still a viable option.

**Comment by frisi** [comment]
taken - i already read this issue before filing this ticket.

when using host networking in a docker swarm this requires to run+configure a separate load balancer.

having an all-in one solution that exposes combined metrics for all processes within this container (maybe discriminated by `process` see below) would be the best approach.

```
thumbor_response_bytes_total{extension="jpg",instance="host1",job="fe_thumbor", process="1"}
thumbor_response_bytes_total{extension="jpg",instance="host1",job="fe_thumbor", process="2"}
thumbor_response_bytes_total{extension="jpg",instance="host2",job="fe_thumbor", process="1"}
thumbor_response_bytes_total{extension="jpg",instance="host2",job="fe_thumbor", process="2"}
```

do you agree with that (not taking into account who will implement that)?

as long as this is not fixed/changed i'd say we need to document that metrics only work for NUM_PROCESSES=1

```
METRICS: "tc_prometheus.metrics.prometheus_metrics"
```
is not compatible with `THUMBOR_NUM_PROCESSES` > 1

**Comment by gingerlime** [comment]
Yes, it sounds nice if it's possible, although I imagine metric systems should be able to aggregate data from different processes/hosts anyway? so as long as you can feed it into something, the aggregation can be done there? I'm not that familiar with prometheus etc unfortunately. Also, it sounds like something to bring with the core thumbor project to me.

As far as making the documentation clearer, 👍 definitely. Do you want to create a PR with the updates you think are missing?

**Comment by savar** [comment]
The issue here is, that prometheus is a `pull` system. So it is exactly NOT something like `statsd` and friends. As the thumbor processes are independent of each other there is no easy way.

One possible solution comes to my mind:

1. change the startup to configure the prometheus port by giving each thumbor instance a different metrics port
2. start a prometheus instance in the thumbor docker container and configure it to scrape all the internal thumbors
3. enable the [federation endpoint](https://prometheus.io/docs/prometheus/latest/federation/) on this internal prometheus and expose this prometheus to the outside world (outside the container)
4. configure an external prometheus to scrape the internal prometheus

**Comment by kkopachev** [comment]
Another solution would be to run sidecar container with https://github.com/prometheus/statsd_exporter . Thumbor writes metrics in statsd format there and exporter exposes aggregated metrics through prometheus protocol.

**Comment by gingerlime** [comment]
Hey @kkopachev 👋 great to hear from you again and happy new year!

This sounds like the most elegant solution to me. But l don’t have any firsthand experience with thumbor stats...

**Comment by gingerlime** [comment]
I'll close this for now, but if it's still something worth discussing, I'm happy to re-open.
