### ISSUE TITLE
Using with local development

### ISSUE THREAD

**Issue by nibsirahsieu** [MinimalCompact/thumbor#95]
Hi Dev,

Thanks for this awesome project. This is my first time using this project.
Currenty i'm trying to use in my local dev environment, but i always hit by these errors:

```
2021-04-07 03:36:52 thumbor:WARNING ERROR retrieving image http://localhost:9080/api/files/7e79c8f7-ce18-4fe2-8752-47b2c17f1763.jpeg: [Errno 99] Cannot assign requested address

2021-04-07 03:36:52 tornado.access:ERROR 504 GET /unsafe/40x40/smart/http://localhost:9080/api/files/7e79c8f7-ce18-4fe2-8752-47b2c17f1763.jpeg (172.17.0.1) 12.67ms
```

Here is my example url: `http://localhost:9070/unsafe/40x40/smart/http://127.0.0.1:9080/api/files/7e79c8f7-ce18-4fe2-8752-47b2c17f1763.jpeg`.

Thanks in advance.

**Comment by gingerlime** [comment]
@nibsirahsieu can you check the README about running it and see if it works with the examples on the README?

If you're still having trouble, then could post a sample docker-compose.yml file that reproduces the issue you're experiencing? this can certainly help troubleshooting things.

**Comment by nibsirahsieu** [comment]
Hi @gingerlime , thanks for your response.

I install thumbor using `docker run -d --name=thumbor -p 9070:80 minimalcompact/thumbor`. It's works well if i pick random image from the internet, but it always fail when the images come from my app.

Basically, i have an application running on my local machine (http://127.0.0.1:9080), not in the docker container.
Does  my app and thumbor should live in the same container?

**Comment by nibsirahsieu** [comment]
Same issue here :

https://github.com/APSL/docker-thumbor/issues/85

**Comment by gingerlime** [comment]
@nibsirahsieu I would suggest reading about docker compose or how docker handles networks. You can't simply access your localhost from a docker container without explicitly setting things up to work.

You can also see some example recipes, for example [this one](https://github.com/MinimalCompact/thumbor/blob/master/recipes/docker-compose/simple/docker-compose.yml)

APSL/docker-thumbor is no longer maintained as far as I'm aware.

**Comment by nibsirahsieu** [comment]
Hi @gingerlime , thanks for your explanation
